onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /vsi_suspi/dut/bb_clk_in
add wave -noupdate /vsi_suspi/dut/strobe_1mhz
add wave -noupdate /vsi_suspi/dut/strobe_4mhz
add wave -noupdate /vsi_suspi/dut/rst_h
add wave -noupdate /vsi_suspi/dut/strobegen_1mhz/rst_l
add wave -noupdate /vsi_suspi/databyte_received
add wave -noupdate /vsi_suspi/dut/DATA1
add wave -noupdate /vsi_suspi/dut/DATA2
add wave -noupdate /vsi_suspi/dut/COM1
add wave -noupdate /vsi_suspi/dut/COM2
add wave -noupdate /vsi_suspi/dut/CODING
add wave -noupdate /vsi_suspi/dut/DECODING
add wave -noupdate /vsi_suspi/dut/FLAG_DATA_OUT
add wave -noupdate /vsi_suspi/dut/rd_addr
add wave -noupdate /vsi_suspi/dut/ram_rd_rq
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_OUT
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/fsm_tx_state
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/reg_BIT_SR
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/reg_BIT_BUSY
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/flag_data_out
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/flag_error
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/reg_TX_STR
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_MARKER
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_MARKER_END
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_DATA1
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_DATA2
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_DATA_END
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_CRC
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/FSM_TX_CRC_END
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_STR
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_FLAG
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_BYTE_NUMBER
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_RAM_RDY_RD
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_RAM_ADDR_OUT
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/TX_RAM_DATA_IN
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/CODING
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/test
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/rs_coder_CODING
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/rs_coder_FULL
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/rs_coder_TIME_OUT
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/coder_data_in
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/crc16_coder_data_out
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/coder_wr_in_dff
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/fsm_state
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/crc_en
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/flag_tx_count
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/tx_count
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/reg_tx_flag
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/reg_tx_byte_number
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/coder_wr_in
add wave -noupdate /vsi_suspi/dut/hi_speed_protocol_rx_inst/mod_hi_speed_protocol_coder_inst/reg_data
add wave -noupdate /vsi_suspi/send_command/crc
add wave -noupdate /vsi_suspi/packet_marker
add wave -noupdate /vsi_suspi/packet_flag
add wave -noupdate /vsi_suspi/packet_length_high
add wave -noupdate /vsi_suspi/packet_length_low
add wave -noupdate /vsi_suspi/packet_data
add wave -noupdate /vsi_suspi/packet_data_index
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {104116995 ps} 0} {{Cursor 2} {22498117613 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 591
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {22445705043 ps} {22692331314 ps}
